name: imager
version: 4.0.15
description: 
homepage:
documentation: 

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  meta: ^1.3.0
  xml: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  lints: ^2.0.1
  test: ^1.16.0
